USE [DR2_Def]
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[dbo].[TB_DefRes]') AND [Name] = 'AddResNo1')
BEGIN
	ALTER TABLE [dbo].[TB_DefRes] ADD AddResNo1 INT CONSTRAINT DF_TB_DefRes_AddResNo1 NOT NULL DEFAULT((0))
	ALTER TABLE [dbo].[TB_DefRes] ADD AddResNo2 INT CONSTRAINT DF_TB_DefRes_AddResNo2 NOT NULL DEFAULT((0))
	ALTER TABLE [dbo].[TB_DefRes] ADD AddResNo3 INT CONSTRAINT DF_TB_DefRes_AddResNo3 NOT NULL DEFAULT((0))
END
