USE [DR2_User]
/****** Object:  StoredProcedure [dbo].[UP_CS_MODIFY_CASH_RANK]    Script Date: 03/31/2009 14:04:19 ******/

IF EXISTS(SELECT * FROM sys.all_objects WHERE object_id = OBJECT_ID(N'UP_CS_MODIFY_CASH_RANK'))
BEGIN
	DROP PROCEDURE [dbo].[UP_CS_MODIFY_CASH_RANK]
END
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[UP_CS_MODIFY_CASH_RANK]
	@CHARGUID UNIQUEIDENTIFIER,
	@ISVISABLE TINYINT,
	@CASH BIGINT
AS
SET NOCOUNT ON;

DECLARE @LASTMODIFYTIME DATETIME
DECLARE @STATE BIT

SELECT @STATE = ISVISABLE,@LASTMODIFYTIME = MODIFYDATE FROM DBO.TB_USERCASH_RANK WHERE CHARGUID = @CHARGUID
IF @@ROWCOUNT = 0
BEGIN

	IF @ISVISABLE = 1
	BEGIN
		INSERT INTO DBO.TB_USERCASH_RANK (CHARGUID,ISVISABLE,USEDCASH)
		VALUES (@CHARGUID,1,@CASH)
		SELECT @@ERROR
	END
	ELSE
	BEGIN
		SELECT 7
		RETURN
	END
END

ELSE
BEGIN

	IF @STATE = 0 AND DATEDIFF(DAY,@LASTMODIFYTIME,GETDATE()) < 7
	BEGIN
		IF @ISVISABLE = 1
		BEGIN
			SELECT 8
			RETURN		
		END
		IF @ISVISABLE = 0
		BEGIN
			SELECT 7	-- 랭킹에 등록되지 않은 캐릭터 입니다.
			RETURN
		END
	END
	
	IF @ISVISABLE = 100
	BEGIN
		UPDATE DBO.TB_USERCASH_RANK SET USEDCASH = USEDCASH + @CASH WHERE CHARGUID = @CHARGUID
		SELECT @@ERROR
	END

	ELSE
	BEGIN
		UPDATE DBO.TB_USERCASH_RANK SET ISVISABLE = @ISVISABLE, MODIFYDATE = GETDATE() WHERE CHARGUID = @CHARGUID
		SELECT @@ERROR
	END
	
END





GO